# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: node_js
      node_js: 14
      python: "3.9.6"
      addons:
        sonarcloud:
          organization: swsnu
          token:
            secure: "Fpo0oHkgTtRGnRzUgGqMI2eynkw1/rd+HaRKgSYZ6brRtAxGHNgjvgVGoXgMHjRYXLEerPDzl6SIrFjp1C4wxPE7fzjoMz5qGRwX+MHBCiFg3NlRvE4IOe66q76De1qZZ5fD3Ym1Z/RuBREIZDOTOOYvDfDT28tCQ03mjhr8TXbEzqIb3rG8iSxlg9A2djloAXQZe6HnTLicdhEqMIJ8D22vF7Tyu59WyElxaw+CC5BvjBX/R1KcT6V3/k6YwatFr6AvZR4Zp7hXlNRJBa5S7jkjWap+BIPR+IboAudVkHtHsz218hcPsfBqZA+ReolEPflpMBleAbu4sVsDAWQMkGL/7bU/j93ehOQempnn6Wf6GyIK61Ra1i+qfBw6JkIB4xuMIGQ4k82klNi4DqLRlXimUkMBg7/Z4iJ2+Go4edFHklIWVpCRyITaSHMI8oKL3axSkAXMi1kBR40r5W/hpB0U9VrJ6gKfNFA/RG9LJzZqogMAD2CFa2jSygxTOR91dEij6Dj974r5PrE2PaQMjzX39A/T2LbLVjKM7U1IVMQoXlK4cJ+ak0uuZCYvClS4l/FMDhSQRnHjxg7NBHELZ0dkVz1i2J6OKqVKVRoIY4S3zJBdNGtn9glqpqMWV9zrMSZeiThGnRTpQEnphGazGaxujXFsI3gRGgOUfU1Sns4="
      install:
        - curl -sSf --retry 5 -o python-3.9.6.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/18.04/x86_64/python-3.9.6.tar.bz2
        - sudo tar xjf python-3.9.6.tar.bz2 --directory /
        - source ~/virtualenv/python3.9/bin/activate
        - cd backend/babchingu
        - pip install -r requirements.txt
        - pip install coveralls
        - cd ../
        - cd ../frontend
        - yarn install
        - yarn global add coveralls
        - gem install coveralls-lcov
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ../backend/babchingu
        - python manage.py makemigrations
        - python manage.py migrate
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - coveralls --merge=../../frontend/coverage.json
        - cd ..
        - cd .. && sonar-scanner
