# Generated by Django 4.1.2 on 2022-12-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='', max_length=130),
        ),
    ]
