# Generated by Django 4.1.2 on 2022-11-17 03:04

from django.db import migrations, models
import mypage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='time_table',
            field=models.JSONField(default=mypage.models.timeTable_default),
        ),
    ]
