# Generated by Django 4.1.2 on 2022-11-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_remove_user_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default='', max_length=3),
        ),
    ]
