# Generated by Django 4.1.2 on 2022-11-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_remove_userinfo_first_name_remove_userinfo_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
