# Generated by Django 4.1.2 on 2022-11-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_userinfo_evaluation_num'),
        ('mypage', '0003_userinfo_nickname'),
    ]

    operations = [
    ]
