# Generated by Django 4.1.2 on 2022-11-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_merge_20221124_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth',
            field=models.CharField(default='000101', max_length=6),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
