# Generated by Django 4.1.2 on 2022-11-26 07:47

from django.db import migrations, models
import mypage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_merge_20221124_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='blocked_users',
            field=models.JSONField(default=mypage.models.empty_list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='matched_users',
            field=models.JSONField(default=mypage.models.empty_list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='unevaluated_users',
            field=models.JSONField(default=mypage.models.empty_list),
        ),
    ]
