# Generated by Django 4.1.3 on 2022-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodayMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealtype', models.CharField(max_length=120)),
                ('menuplace', models.CharField(max_length=120)),
                ('menuname', models.CharField(max_length=120)),
                ('menuprice', models.CharField(max_length=120)),
                ('menuextra', models.CharField(max_length=200)),
            ],
        ),
    ]
