# Generated by Django 4.1.2 on 2022-11-08 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chatusers',
            field=models.ManyToManyField(related_name='chatroom_with_this_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
