# Generated by Django 4.1.2 on 2022-11-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chatuser1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='chatuser2',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='roomtype',
            field=models.CharField(default='개인', max_length=120),
        ),
    ]
