# Generated by Django 4.1.2 on 2022-10-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_matching', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='matchingentity',
            name='age_wanted',
        ),
        migrations.AddField(
            model_name='matchingentity',
            name='age_wanted_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchingentity',
            name='age_wanted_to',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='matchingentity',
            name='matched_opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.matchingentity'),
        ),
        migrations.AlterField(
            model_name='matchingentity',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchingentity',
            name='user_mbti',
            field=models.CharField(max_length=4),
        ),
        migrations.AddField(
            model_name='matchingentity',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='matching.matchingqueue'),
        ),
    ]
