# Generated by Django 4.1.2 on 2022-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_groupmatchingqueue_groupmatchingentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmatchingentity',
            name='matched_opponents',
            field=models.JSONField(default=[]),
        ),
    ]
