# Generated by Django 4.1.2 on 2022-11-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchingqueue_remove_matchingentity_age_wanted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingqueue',
            name='num_matching',
        ),
    ]
