# Generated by Django 4.1.2 on 2022-11-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_groupmatchingentity_matched_opponents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmatchingentity',
            name='matched_opponents',
            field=models.JSONField(),
        ),
    ]
