# Generated by Django 4.1.2 on 2022-11-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_alter_groupmatchingentity_matched_opponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmatchingentity',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchingentity',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
